### ISSUE TITLE
Strong name is required in many situations

### ISSUE THREAD

**Issue by TrabacchinLuigi** [charri/Font-Awesome-WPF#14]
Strong name the assembly or it would not be usable in many situations

**Comment by charri** [comment]
this is definitely something I will look into.

**Comment by TrabacchinLuigi** [comment]
is there any way i can help with that ? 
Do you have some special requirement ?
Like keeping secret the key while keeping everything open source ?

**Comment by charri** [comment]
Hi @TrabacchinLuigi, could you try this nuget package: https://www.nuget.org/packages/FontAwesome.WPF.Signed/

I opted in creating a seperate package, so developers can use either the signed or unsigned version.

What do you think?

**Comment by TrabacchinLuigi** [comment]
Sure i will! Monday!

**Comment by TrabacchinLuigi** [comment]
Good seems everything i working fine with the new version.
I think that having two nuget packages is useless, can't see any advantage in using a non-signed version ... i would just go over the current package...

**Comment by charri** [comment]
this is something i would merge yes. just didn't want to f-up the "main" and stable version.

**Comment by bzuillsmith** [comment]
Could this be reopened until it's published in the regular package? A strong-named (signed) dll only allows references to other strong-named dlls so this is a pretty big issue. It would be helpful to be notified through this thread when you have this published in the main nuget package. For now, I'm also using the signed package

**Comment by TrabacchinLuigi** [comment]
Yes, would be nice to receive a notification so I'll reopen my solutions and change package

**Comment by charri** [comment]
will close once merged.

**Comment by charri** [comment]
As of 4.5.0.7 (commit 9382c418669df543f70cad61fa8b1a0212d99bd9) dlls will be signed.
