### ISSUE TITLE
Cannot resolve schemas.fontawesome.io

### ISSUE THREAD

**Issue by ephracis** [charri/Font-Awesome-WPF#15]
I have added FontAwesome.WPF via Nuget (version 4.4.0.5). I'm getting the following errors when trying to use it inside my XAML:

> The type 'fa:FontAwesome' was not found. Verify that you are not missing an assembly reference and that all referenced assemblies have been built.
> Unknown type 'FontAwesome' in XML namespace 'http://schemas.fontawesome.io/icons/'

When I try to ping `schemas.fontawesome.io` it fails to resolve the name.

**Comment by charri** [comment]
Hi @ephracis, the `schemas.fontawesome.io` is just a pseudo namespace (there is no http://schemas.fontawesome.io). What VS version are you using? I have tried both VS2013 + VS2015 and all seem to work for me.
