### ISSUE TITLE
Example project doesn't build.

### ISSUE THREAD

**Issue by sebascomeau** [charri/Font-Awesome-WPF#19]
The example project doesn't build. 

Here's the error list:

![image](https://cloud.githubusercontent.com/assets/2814465/10542117/4105a54a-73ec-11e5-87ae-16460d99a930.png)

**Comment by punker76** [comment]
@sebascomeau that's cause the example resolves the NuGet dll and doesn't use the compiled dll. For fast workaround, just compile the FontAwesome dll by yourself and reference it manually.

**Comment by charri** [comment]
@sebascomeau as this problem has occured in the past, the example project now references the FontAwesome project in the src folder instead of the nuget. Pull to get the latest and greatest! :+1:  :)

**Comment by CADbloke** [comment]
Build is still broken. But thanks for making this. 

Steps to repo...

1. Clone
1. Open `Font-Awesome-WPF\example\Example.FontAwesome.WPF.sln`
1. Build.
1. Tried restoring  Nuget etc. Nup.

![fontawesomewpfexamplebuilderrors](https://cloud.githubusercontent.com/assets/147329/12258224/1e4f67ce-b961-11e5-94b3-a101ee4ce31b.png)



```bat
1>------ Build started: Project: FontAwesome.WPF.NET40, Configuration: Debug Any CPU ------
1>Build started 12/01/2016 7:05:36 PM.
1>ResolveAssemblyReferences:
1>  A TargetFramework profile exclusion list will be generated.
1>C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\Microsoft.WinFx.targets(711,5): error BG1002: File '..\..\Font-Awesome\fonts\FontAwesome.otf' cannot be found.
1>
1>Build FAILED.
```

**Comment by charri** [comment]
this is because the FontAweseom submodul is not loaded:
```
git clone --recursive git://github.com/foo/bar.git
```

**Comment by CADbloke** [comment]
Thanks. LUser.FAIL - Tortoisegit doesn't do that  automagically,

For all you other LUsers out there - http://stackoverflow.com/questions/16058917/pulling-git-submodules-with-tortoisegit

TGit has a ticket open for this: https://gitlab.com/tortoisegit/tortoisegit/issues/1888
