### ISSUE TITLE
NOT AN ISSUES - How to add new glyph/icons with this project?

### ISSUE THREAD

**Issue by Simonlabdes** [charri/Font-Awesome-WPF#28]
Hi!  I know it is not a issue, but I dont know how to ask a question on git-hub...sorry..!

So I just wanted to know if and how we can add new icons to the set of icons found here? 

thanks!

**Comment by charri** [comment]
A bit out-of-scope for this project :)

this project uses icons from [font-awesome](http://fontawesome.io/).
If you have your own glyph font then you could just replace the font file and map the unicode character to an enum. (its all in the source)

Closing here as out-of-scope
