### ISSUE TITLE
Scaling down image messes with icon weights

### ISSUE THREAD

**Issue by drewnoakes** [charri/Font-Awesome-WPF#33]
`ImageAwesome` internally renders the glyph at 100x100 px, then scales it down to the target size (assuming it's less than 100px).

However this messes with the font weights. Consider this example ([from here](http://fontawesome.io/icon/random/)):

![image](https://cloud.githubusercontent.com/assets/350947/18826080/7b57c3e4-83c3-11e6-8b70-615362232266.png)

At small sizes, the typeface designer provides hints on how to map lines and details to pixels. At larger sizes, the icon _feels_ heavier. When you scale it down, it ends up looking bold, fuzzy and without sharp detail.

Instead, `ImageAwesome` should render at the required size, so no scaling occurs. The underlying `Image.StretchDirection` should have its metadata overridden, setting the default to `StretchDirection.None`.

Crisp icons at 96 DPI due to typeface hinting is one of the reasons to use fonts over the equivalent paths/geometry. By rendering the glyph at the wrong size, this benefit goes away.

**Comment by charri** [comment]
Cool, thanks for this! I'll look into getting this implemented.

**Comment by charri** [comment]
![image](https://cloud.githubusercontent.com/assets/5507128/19281918/91c882be-8fec-11e6-8008-2dddfb43ac64.png)

@drewnoakes the top images is rendering the icons on OnDraw to the current Height + Width of the Element. the 2nd image renders as "normal"

To me, they look the same?

**Comment by drewnoakes** [comment]
Those do look very similar :)

Have you tested on a high DPI screen? I can do that if you push code to a
branch.

**Comment by charri** [comment]
fixed in v4.7
