### ISSUE TITLE
How to use FontAwesome.WPF when image source URI is required

### ISSUE THREAD

**Issue by afluegge** [charri/Font-Awesome-WPF#34]
I have a situation where I need a URI as an IconSource.  How can I use FontAwesom.WPF in this situation?

Details:
"Extended WPF Toolkit" AvalonDock LayoutAnchorable has a property to set the panel icon ("IconSource") which requires a URI.  The property does not allow binding.  I want to use a FontAwesom icon as the panel icon.
```xml
<xcad:DockingManager>
    <xcad:LayoutRoot x:Name="LayoutRoot">
        <xcad:LayoutPanel Orientation="Horizontal">
            <xcad:LayoutAnchorablePane DockMinWidth="200">
                <xcad:LayoutAnchorable ContentId="Properties" Title="Properties" IconSource=" ??? ">
                    . . .
                </xcad:LayoutAnchorable>
            </xcad:LayoutAnchorablePane>
        </xcad:LayoutPanel>
    </xcad:LayoutRoot>
</xcad:DockingManager>

```

**Comment by charri** [comment]
This is currently not supported. Easiest method would be to download the image you need (http://fa2png.io/).

**Comment by DesselBane** [comment]
Can you use a Resource (Static or Dynamic) ?
Then you could use a MarkupExtension which I suggested [(here)](https://github.com/charri/Font-Awesome-WPF/issues/27) to get the FA into an ImageSource
