### ISSUE TITLE
FontAwesome 4.7/4.6

### ISSUE THREAD

**Issue by robertmuehsig** [charri/Font-Awesome-WPF#35]
Hi

I noticed that there are a bunch of nice new icons added in FontAwesome 4.6/4.7 and I would like to help to update this project to the most recent fontawesome version. 

Are these the correct steps?

* Update the FontAwesome submodule to the most recent version
* Use FontAwesome.Generate with the src\icons.yml
* Update the FotnAwesomeIcon.cs files with the generated one
* Update the nuspec files 
* make pull request

Regarding the NuGet version - did you align the version number to the FontAwesome version number or was there semver in mind?

**Comment by robertmuehsig** [comment]
I noticed that there is a similar project - so I'm fine with [that](https://github.com/MahApps/MahApps.Metro.IconPacks) project as well ;)

**Comment by dnxit** [comment]
@robertmuehsig thanks for the link to MahApps.Metro.IconPacks
I was waiting for the update as well 👍 will switch now
