### ISSUE TITLE
Adapting parent foreground

### ISSUE THREAD

**Issue by Matt-17** [charri/Font-Awesome-WPF#50]
When using in other control (like ContentControl) ImageAwesome does not use the foreground provided by the parent. 

Example: 

        <ContentControl Foreground="Red">
            <TextBlock Text="FontAwesome" />
        </ContentControl>`

This gives you a red TextBlock. 

        <ContentControl Foreground="Red">
            <fa:ImageAwesome Icon="FontAwesome" />
        </ContentControl>`

This gves you a black image, which should be red.

_I'm using FontAwesome.WPF in version 4.7.0.9_

**Comment by helluvamatt** [comment]
Use `fa:FontAwesome` which extends from `TextBlock`.

Example:

```
<ContentControl Foreground="Red">
    <fa:FontAwesome Icon="FontAwesome">
</ContentControl>
```
