### ISSUE TITLE
Icons not visible in design time (UWP)

### ISSUE THREAD

**Issue by danbord** [charri/Font-Awesome-WPF#51]
The icons works fine when in runtime.  But at design time they're not visible, making the design pretty annoying.  I'm using VS2017 Community Edition.

Here's my Xaml
`<fa:FontAwesome Icon="Backward" Foreground="Black"  />`

**Comment by vavsab** [comment]
Try install the font to your system. It seems to be a designer bug. Anyway let me know if you have another workaround. I will also apply it to my project.

**Comment by danbord** [comment]
By Installing the font on the system, you mean download FontAwesome font and double click to install the otf or ttf file?  Tried that but not working for me :/

**Comment by vavsab** [comment]
Yes, exactly. Strange... Have you tried to restart PC after that? 
I have not noticed that you are using UWP. It worked on WPF for me.

**Comment by danbord** [comment]
FINALLY found it!  Seems like it doesn't play nice with x64 compiling... Just by changing my project configuration to x86 fixed it (the combobox next to the Debug combobox, not in project settings).

else than that, I found that article that lead me to my answer : http://blog.galasoft.ch/posts/2016/02/enabling-disabling-design-data-in-visual-studio-2015-update-1/
