### ISSUE TITLE
Example doesn't build

### ISSUE THREAD

**Issue by pushrbx** [charri/Font-Awesome-WPF#6]
In the newer version (4.2.0.2) the example doesn't build. The Spin property is missing, and the references are incorrect in the xaml files.

![image](https://cloud.githubusercontent.com/assets/6832715/6080581/952a31e8-ae0a-11e4-8632-c01058c6e5cf.png)

Visual Studio 2013 Ultimate

**Comment by charri** [comment]
Thank you for your comment.

I was able to verify the problem. will have a more detailed look tomorrow. Until then i advise to change the xaml namespace reference from

```
xmlns:fa="http://schemas.fontawesome.io/icons/"
````
to
```
xmlns:fa="clr-namespace:FontAwesome.WPF;assembly=FontAwesome.WPF"
````

it should work like that.

**Comment by charri** [comment]
basically the packages.config was referencing to an obsolete package. the example has been fixed. you will need to restore the nuget packages, remove the old package from nuget's package folder. If visual studio still complains, clean the solution and restart visual studio (did the trick for me)
